**Домашнее задание 1**

Решите предложенные задания с использованием модуля NumPy. Использование условий и циклов крайне нежелательно (списковые включения это тоже цикл!), за это будут снижаться баллы.
Все задания равноценны. В каждой задаче постарайтесь придумать несколько решений. В задачах, где обязательно необходимо предложить хотя бы два решения, об этом написано. Решением должен быть Jupyter notebook / ссылка на Colab

Под массивом (если не указано иное), понимается одномерный массив. Для большей части задач не указан размер массива. Это значит, что код должен работать корректно для любого размера массива

1. Создайте массив 3x3, состоящий из True. Напишите минимум два варианта решения


In [6]:
import numpy as np
import timeit

In [3]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

2. Замените в массиве все нечетные положительные числа на -1

In [19]:
a = np.random.randint(low=-10, high=10, size=10)
print(a)
a[(a > 0) & (a % 2 == 1)] = -1
print(a)

[ 0 -7  8  6 -6  9  7  9  4  7]
[ 0 -7  8  6 -6 -1 -1 -1  4 -1]


3. Найдите все числа, встречающиеся в 1 и 2 массивах

In [20]:
arr1 = np.random.randint(low=-10, high=10, size=10)
arr2 = np.random.randint(low=-10, high=10, size=10)
print(arr1, arr2)
np.intersect1d(arr1, arr2)

[-8 -6  4 -4 -8  3 -8 -3  2  1] [-10   1  -6   8  -9  -8   7   2  -2  -2]


array([-8, -6,  1,  2])

4. Дана функция maxx, работающая с двумя числами. Напишите обертку над ней, которая будет работать с двумя np.array (одинакового размера) и будет применять функцию maxx поэлементно (вместо maxx может быть любая другая кастомная функция)


```
def maxx(x, y):
	    return x if x >= y else y
```




In [22]:
def maxx(x, y):
        return x if x >= y else y


arr1 = np.random.randint(low=-10, high=10, size=10)
arr2 = np.random.randint(low=-10, high=10, size=10)
print(arr1, arr2)

func1 = np.vectorize(maxx)
func1(arr1, arr2)

[  3   8  -8   0 -10  -3  -9  -3  -5   8] [-9 -1 -5 -6  1 -4 -5 -5 -8  2]


array([ 3,  8, -5,  0,  1, -3, -5, -3, -5,  8])

5. Дана матрица 3х3. Поменяйте местами 1 и 2 столбцы матрицы.

In [46]:
arr1 = np.random.randint(low=-10, high=10, size=(3, 3))
arr1

array([[-2,  5, -7],
       [-5, -1, -3],
       [ 3, -1, -5]])

In [47]:
arr1[:, [1, 0]] = arr1[:, [0, 1]]
arr1

array([[ 5, -2, -7],
       [-1, -5, -3],
       [-1,  3, -5]])

6. Поменяйте опции (```np.set_printoptions```), чтобы при выводе numpy.array отображалось не более 6 элементов

In [50]:
np.set_printoptions(threshold=6)
np.random.randint(low=-10, high=10, size=10)

array([ 4,  7,  6, ..., -5,  8, -8])

7. В данном массиве замените все числа, меньшие 0 на 0, а большие 255 на 255. Напишите минимум два варианта решения

In [57]:
arr = np.random.randint(low=-500, high=500, size=500)
arr

array([ -40,  325, -427, ...,   85,  307, -155])

In [58]:
arr[(arr < 0)] = 0
arr[(arr > 255)] = 255
arr

array([  0, 255,   0, ...,  85, 255,   0])

In [59]:
arr = np.where(arr > 255, 255, arr)
arr = np.where(arr < 0, 0, arr)
arr

array([  0, 255,   0, ...,  85, 255,   0])

8. Выведите позиции топ-5 максимальных элементов в массиве. Попробуйте решить задачу за линейную сложность относительно числа элементов

In [68]:
arr = np.random.randint(low=-500, high=500, size=6)
arr

array([-135, -177, -168,  437,  337, -472])

In [72]:
arr[np.argpartition(arr, -5)[-5:]]

array([-177, -168,  437,  337, -135])

9. Преобразуйте массив массивов в одномерный массив.

In [73]:
arr = np.random.randint(low=-500, high=500, size=(4, 5))
arr

array([[-368, -307, -238,  348, -293],
       [ 117,  -34, -484,  163,  -67],
       [-438,  433,  250,  342, -162],
       [-322, -120,  480,  234,  -58]])

In [74]:
arr = np.concatenate(arr)
arr

array([-368, -307, -238, ...,  480,  234,  -58])

10. Найдите максимум в каждой строке двумерного массива

In [76]:
arr = np.random.randint(low=-500, high=500, size=(2, 5))
arr

array([[ 261,  321,  454,  -29,  135],
       [ 101,   14,   23,  301, -169]])

In [78]:
np.amax(arr, axis=1)

array([454, 301])

11. Удалите все np.nan из массива

In [80]:
arr = np.array([np.nan, 1, 2, 3, 4, 5, np.nan])
arr

array([nan,  1.,  2., ...,  4.,  5., nan])

In [84]:
arr[~np.isnan(arr)]

array([1., 2., 3., 4., 5.])

12. Найдите индекс пятого повторения числа 1 в массиве (считаем, что в массиве есть хотя бы пять единиц)

In [93]:
arr = np.random.randint(low=0, high=2, size=100)
arr

array([1, 1, 0, ..., 1, 1, 1])

In [101]:
np.where(arr == 1)[0][5]

7

13. В квадратной матрице 5х5 из нулей получить ромб из 1, который касается середин сторон квадрата. Решите задачу как для полного ромба (внутри все 1), так и для полого (1 по границе, внутри 0):

```
полный           полый
0 0 1 0 0       0 0 1 0 0 
0 1 1 1 0       0 1 0 1 0 
1 1 1 1 1       1 0 0 0 1 
0 1 1 1 0       0 1 0 1 0 
0 0 1 0 0       0 0 1 0 0 
```

In [190]:
r1 = np.zeros((5, 5), dtype=int)
r1[1:-1, 1:-1] = 1
r1[:,[2]] = 1
r1[[2],:] = 1
r1

array([[0, 0, 1, 0, 0],
       [0, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [0, 1, 1, 1, 0],
       [0, 0, 1, 0, 0]])

In [192]:
r1[1:-1, 2] = 0
r1[2, 1:-1] = 0
r1

array([[0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0]])

14. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки

In [133]:
arr = np.random.randint(low=1, high=101, size=(5, 7))
arr

array([[65, 20, 27, ..., 84, 32, 95],
       [60, 43, 40, ..., 34, 85, 60],
       [54, 53, 94, ..., 60,  2, 26],
       [68,  7, 32, ..., 95, 61,  1],
       [83, 90, 47, ..., 97, 99, 17]])

In [135]:
arr = np.delete(arr, [3,5], axis=1)
arr

array([[65, 20, 27, 84, 95],
       [60, 43, 40, 34, 60],
       [54, 53, 94, 60, 26],
       [68,  7, 32, 95,  1],
       [83, 90, 47, 97, 17]])

15. Вычислите [скользящее среднее](https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%BE%D0%BB%D1%8C%D0%B7%D1%8F%D1%89%D0%B0%D1%8F_%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D1%8F%D1%8F) в окне ширины 3

In [137]:
arr = np.random.randint(low=1, high=101, size=6)
arr

array([14, 41, 32, 69, 88, 56])

In [143]:
np.convolve(arr, np.ones(3, dtype=int), 'valid') / 3

array([29.        , 47.33333333, 63.        , 71.        ])